DROP TABLE major.actions CASCADE;
DROP TABLE major.atbats CASCADE;
DROP TABLE major.divisions CASCADE;
DROP TABLE major.games CASCADE;
DROP TABLE major.leagues CASCADE;
DROP TABLE major.pitches CASCADE;
DROP TABLE major.players CASCADE;
DROP TABLE major.runners CASCADE;
DROP TABLE major.teams CASCADE;
DROP TABLE major.venues CASCADE;
DROP TABLE major.seasons CASCADE;

DROP TABLE minor.actions CASCADE;
DROP TABLE minor.atbats CASCADE;
DROP TABLE minor.games CASCADE;
DROP TABLE minor.pitches CASCADE;
DROP TABLE minor.runners CASCADE;
DROP TABLE minor.seasons CASCADE;
DROP TABLE minor.sports CASCADE;